language: node_js

node_js:
  - '10'

script:
  - npm ci
  - npm run lint
  - npm run build

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: npm run deploy
#   on:
#      branch: master